### ISSUE TITLE
all links not working after update

### ISSUE THREAD

**Issue by maninthemiddle01** [Automattic/wordpress-activitypub#1393]
### Quick summary

After updating ActivityPub, all website links returned "page not found" errors. This happens with literally every update, actually 3 times since yesterday. 

### Steps to reproduce

1. Have a working WordPress site with ActivityPub plugin installed
2. Update ActivityPub plugin
3. Try to visit any page/post on the site
4. Observe that all links return "page not found" errors

### Site owner impact

More than 60% of the total website/platform users

### Severity

Critical

### What other impact(s) does this issue have?

Platform revenue

### If a workaround is available, please outline it here.

The issue was resolved every time by visiting Settings -> Permalinks and clicking "Save Changes" without making any changes.
The issue appears to be related to WordPress rewrite rules not being properly flushed during the plugin update. While there is a simple workaround, this could be confusing for users and potentially cause temporary site disruption. Consider adding an admin notice after updates to remind users to refresh their permalinks if they experience 404 errors, or ensure rewrite rules are properly flushed during the update process.

**Comment by pfefferle** [comment]
We flush the rewrite rules every time we change something through a migration process.

**Comment by maninthemiddle01** [comment]
Okay, then it must be something else?

**Comment by obenland** [comment]
> all website links returned "page not found" errors. This happens with literally every update, actually 3 times since yesterday.

That sounds pretty fundamental. Since it happened 3 times, I assume it happens outside of a plugin update as well?

**Comment by maninthemiddle01** [comment]
There have been 3 updates of activitypub on the site and immediately after that the links were broken. I  checked directly after the last update, where the error was also reproduced, before the site worked.

**Comment by obenland** [comment]
Did this happen again with the 5.4.0 update?

**Comment by maninthemiddle01** [comment]
Thank you for your message. Unfortunately it happened again with the 5.4.0 and 5.4.1 updates. Maybe it interferes with other plugins? I have Falang installed and I also have the following problem: [https://wordpress.org/support/topic/falang-breaking-calendar-view-switching-after-update/](https://wordpress.org/support/topic/falang-breaking-calendar-view-switching-after-update/)

**Comment by obenland** [comment]
Yeah, hard to tell, I don't know the plugin. Could you try disabling this and other plugins before updating ActivityPub next week and see if that changes things?

**Comment by maninthemiddle01** [comment]
I can try to disable Falang as theeventscalendar is a crucial part of the website. When are you planning to release the update?

**Comment by pfefferle** [comment]
It is already released. With the version `5.4.X` it should be fixed.

**Comment by maninthemiddle01** [comment]
Ok, it worked with Falang being deactivated :)
So now I activated it and will close the issue of this also works. Thank you a lot for your effort, the app and the support for open source software :)

**Comment by maninthemiddle01** [comment]
It seems that the falang plugin is the problem: after activating it the problem reoccurs after updates being installed

**Comment by maninthemiddle01** [comment]
Unfortunately it still occurs. I tried [this](https://github.com/akirk/enable-mastodon-apps/issues/252#issuecomment-2866906924), which apparently seemed to work, but still after an update the error persists. (I couldn't paste the hidden file though, maybe this was the problem and I have to retry it? I'm sorry for being so noobish)
