### ISSUE TITLE
Updates to edited posts not appearing on Fediverse

### ISSUE THREAD

**Issue by aendra-rininsland** [Automattic/wordpress-activitypub#409]
I'm following my WordPress blog from my Mastodon user and AFAICT editing the post in WordPress doesn't push an edited version to the Fediverse — the copy of the post my Mastodon instance has cached doesn't have the changes I've made. 

I think to do this you need to generate a StatusEdit entity on every post edit. See https://docs.joinmastodon.org/entities/StatusEdit.

**Comment by pfefferle** [comment]
This is a known issue and will be fixed in 1.0.0

**Comment by pfefferle** [comment]
should be fixed now! please re-open if not!

**Comment by jonathanmc** [comment]
I seem to still be having this problem. I've looked through all of the current issue pages for a way to force an update and have not been able to find one.

This page I have specifically edited to force an update and the resulting Mastodon post, https://mastodon.social/@Jonathan@jonathan.crookston.ca/112033969812159100, still shows as March 3 version.

I have done a number of edits in the meantime and it has been a few days. I have cleared the WordPress cache.

I have just now tried an edit to the title to see if that will update the feed. I will report back.
