### ISSUE TITLE
`activitypub_post` no longer called?

### ISSUE THREAD

**Issue by janboddez** [Automattic/wordpress-activitypub#465]
### Quick summary

Can't say I fully understand how or why, but on my WordPress, the `activitypub_post` hook no longer gets run. Related issue: #349. (And #464, which I closed, because I was drawing conclusions way too quickly, apparently. :-S)

### Steps to reproduce

Create an mu-plugin, something like:
```
add_filter( 'activitypub_post', function( $array, $post ) {
        error_log( 'This is where you could previously modify, e.g., a post\'s visibility.' );

	return $array;
}, 99, 2 );
```

### What you expected to happen

See the text appear in the logging, or, well, I used to modify certain posts' visibility.

### What actually happened

Nothing.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by janboddez** [comment]
Maybe https://github.com/Automattic/wordpress-activitypub/blob/963b2795a617ca6e94ecd7eb84249b997423c59b/includes/activity/class-activity.php#L203C1-L205C4 has something to do with it too (the visibility tweak no longer working, I mean). It seems the Activity no longer gets to/cc from the array, but from the Post object. Could be nothing tho.

Either way, would be cool if we got to be able to override the to/cc attributes like before.

Guess I might have to revert to an older version then.

**Comment by pfefferle** [comment]
I am sorry, that the hook was removed, I try to re-add it to be downwards compatible.

But there are some new filters you could use: https://github.com/Automattic/wordpress-activitypub/blob/master/includes/activity/class-base-object.php#L662

Because all new Objects in the plugin are a child of the Base-Object, this will be called every time there is a `to_array` or a `to_json` called.

Sorry again!

**Comment by janboddez** [comment]
Awesome. Going to try that later!

Nah, I'm sorry, feel like I'm complaining to much. :-)

(I was confused because the hook still exists in the code, it just seems it never gets triggered.)

**Comment by pfefferle** [comment]
Yes, I only kept the file for backwards compatibility 😅

**Comment by janboddez** [comment]
OK, this works (but it somehow breaks deletes, or maybe they stopped working for another reason):
```
add_filter( 'activitypub_activity_object_array', function( $array, $class, $activity_id, $id ) {
	$post = get_post( url_to_postid( $id ) ); // `$id` is the "object ID," or the post URL.

	if ( ! empty( $post->post_author ) && has_category( 'rss-club', $post->ID ) ) {
		$array['to'] = array( rest_url( "activitypub/1.0/users/{$post->post_author}/followers" ) );
		$array['cc'] = array( 'https://www.w3.org/ns/activitystreams#Public' );
	}

	error_log( print_r( $array, true ) );

	return $array;
}, 99, 4 );
```

**Comment by pfefferle** [comment]
I fixed the delete with the latest PR.

**Comment by janboddez** [comment]
That fixes deletes for me!

**Comment by pfefferle** [comment]
thanks for testing @janboddez !

**Comment by pfefferle** [comment]
can we close this for now?

**Comment by janboddez** [comment]
Yeah, so the old hook I think is still not called, but I guess that's what one can expect from a pre-1.0 (back then) release.

The new hooks work (I updated my add-on plugin), so OK for me.
